export { default as Mgo } from './mgo.jpeg';
export { default as Dgo } from './papa-2.jpeg';
export { default as Choir } from './choir.jpeg';
export { default as Papa } from './papa-headshot-2.png';
export { default as Mama } from './mama-headshot.png';
export { default as Mama3 } from './mama-headshot.jpeg';
export { default as Asst } from './asst-headshot-2.png';
export {default as Daughter} from './d-1.jpeg';
export { default as Banner1 } from './b-1.jpeg';
export { default as Banner2 } from './b-2.jpeg';
export { default as AsstP } from './asst-1.jpeg';
export {default as Together1} from './t-1.jpeg';
export {default as Together2} from './t-2.jpeg';
export {default as Together3} from './t-3.jpeg';
export { default as PapaA } from './papa-a1.jpeg';
export { default as LibP} from './lib-headshot.png';
export {default as Papa2} from './papa-2.jpeg';
export {default as Mama2} from './mama-2.jpeg';
export {default as Mama4} from './mamaD.png';
export {default as Asst3} from './asst-3.jpeg';
export {default as Asst2} from './asst-headshot.jpeg';
export {default as ChoirMistress} from './choirLW.jpeg';
export { default as ChoirMaster } from './choirLM.jpeg';
export {default as ChurchCoordinator} from './churchL.jpeg';
export {default as MediaHead} from './mediaL.jpeg';
export {default as BuildingCoordinator} from './buildingL.jpeg';
export {default as UsherHead} from './usherL.jpeg';
export {default as MenLeader} from './menL.jpeg';
export {default as NigP} from './nigP.jpeg';
export {default as NigPN} from './nigP.png';
export {default as ChildrenMinistry} from './c-1.jpeg';
export {default as ChildrenMinistry2} from './children.jpeg';
export { default as ChildrenH } from './ChildrenH.jpeg';
export { default as FinancialS } from './FinancialS.jpeg';
export { default as RecordsH } from './RecordsH.jpeg';
export { default as RecordsHN } from './RecordsH.png';
export { default as TechH } from './TechH.jpeg';
export { default as Partners1 } from './Partners1.jpeg';
export { default as Image1 } from './image1.jpeg';
export { default as Image2 } from './image2.jpeg';
export { default as Image3 } from './image3.jpeg';
export { default as Image4 } from './image4.jpeg';
export { default as Image5 } from './image5.jpeg';
export { default as Image6 } from './image6.jpeg';
export { default as Image7 } from './image7.jpeg';
export { default as Image8 } from './image8.jpeg';
export { default as Image9 } from './image9.jpeg';
export { default as Image10 } from './image10.jpeg';
export { default as Image11 } from './image11.jpeg';
export { default as Image12 } from './image12.jpeg';
export { default as Image13 } from './image13.jpeg';
export { default as Image14 } from './image14.jpeg';
export { default as Image15 } from './image15.jpeg';
export { default as Image16 } from './image16.jpeg';
export { default as Image17 } from './image17.jpeg';
export { default as Image18 } from './image18.jpeg';
export { default as Image19 } from './image19.jpeg';
export { default as Image20 } from './image20.jpeg';
export { default as Image21 } from './image21.jpeg';
export { default as Image22 } from './image22.jpeg';
export { default as Image23 } from './image23.jpeg';
export { default as Image24 } from './image24.jpeg';
export { default as Image25 } from './image25.jpeg';
export { default as Image26 } from './image26.jpeg';
export { default as Image27 } from './image27.jpeg';
export { default as Image28 } from './image28.jpeg';
export { default as Image29 } from './image29.jpeg';
export { default as Image30 } from './image30.jpeg';
export { default as PapaP } from './papa2.jpeg';
export { default as MamaN } from './mama_new.jpeg';
export { default as UsherHN } from './usher_new.jpeg';
export { default as BennoW } from './benno.jpeg';
export { default as Church1 } from './Church1.jpeg';
export { default as Church2 } from './Church2.jpeg';
export { default as Church3 } from './church3.jpeg';
export { default as Woman1 } from './Woman1.jpeg';
export { default as Man1 } from './Man1.jpeg';
export { default as PraiseImg } from './praise.jpeg';
export { default as AwakenImg } from './awaken.jpeg';