export { default as Mgo } from './mgo.jpeg';
export { default as Dgo } from './papa-2.jpeg';
export { default as Choir } from './choir.jpeg';
export { default as Papa } from './papa-headshot-2.png';
export { default as Mama } from './mama-headshot.png';
export { default as Asst } from './asst-headshot-2.png';
export {default as Daughter} from './d-1.jpeg';
export { default as Banner1 } from './b-1.jpeg';
export { default as Banner2 } from './b-2.jpeg';
export { default as AsstP } from './asst-1.jpeg';
export {default as Together1} from './t-1.jpeg';
export {default as Together2} from './t-2.jpeg';
export {default as Together3} from './t-3.jpeg';
export { default as PapaA } from './papa-a1.jpeg';
export { default as LibP} from './lib-headshot.png';
export {default as Papa2} from './papa-2.jpeg';
export {default as Mama2} from './mama-2.jpeg';
export {default as Asst3} from './asst-3.jpeg';
export {default as ChoirMistress} from './choirLW.jpeg';
export { default as ChoirMaster } from './choirLM.jpeg';
export {default as ChurchCoordinator} from './churchL.jpeg';
export {default as MediaHead} from './mediaL.jpeg';
export {default as BuildingCoordinator} from './buildingL.jpeg';
export {default as UsherHead} from './usherL.jpeg';
export {default as MenLeader} from './menL.jpeg';
export {default as NigP} from './nigP.jpeg';
export {default as ChildrenMinistry} from './c-1.jpeg';
export {default as ChildrenMinistry2} from './children.jpeg';
export { default as ChildrenH } from './ChildrenH.jpeg';
export { default as FinancialS } from './FinancialS.jpeg';
export { default as RecordsH } from './RecordsH.jpeg';
export { default as TechH } from './TechH.jpeg';
export { default as Partners1 } from './Partners1.jpeg';